project:
  type: website
  output-dir: docs

website:
  title: "Stephanie Nguyen"
  navbar:
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - project_workshop.qmd
      - resume.qmd
      - icon: github 
        href: https://github.com/stephanie-t-nguyen
      - icon: linkedin
        href: https://www.linkedin.com/in/stephanie0nguyen/

format:
  html:
    theme: minty
    css: styles.css
    page-layout: full
    toc: true

editor: visual

