project:
  type: website
  output-dir: docs

website:
  title: "Stephanie Nguyen"
  navbar:
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - project_workshop.qmd
      - href: github_website_resume.pdf
        text: resume
      - icon: github 
        href: https://github.com/stephanie-t-nguyen
      - icon: linkedin
        href: https://www.linkedin.com/in/stephanie0nguyen/

format:
  html:
    theme: 
      - mystyles.scss
    mainfont: Source+Sans+Pro
    toc: true

editor: visual

